"""Add order schedule functionality

Revision ID: bbbba3a5b4bc
Revises: 9a68c4c22869
Create Date: 2025-06-18 20:56:42.514171

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'bbbba3a5b4bc'
down_revision = '9a68c4c22869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_schedule',
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('monday', sa.Boolean(), nullable=True),
    sa.Column('tuesday', sa.Boolean(), nullable=True),
    sa.Column('wednesday', sa.Boolean(), nullable=True),
    sa.Column('thursday', sa.Boolean(), nullable=True),
    sa.Column('friday', sa.Boolean(), nullable=True),
    sa.Column('saturday', sa.Boolean(), nullable=True),
    sa.Column('sunday', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('lunch_break_start', sa.Time(), nullable=True),
    sa.Column('lunch_break_end', sa.Time(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(contact_id IS NOT NULL AND organisation_id IS NULL) OR (contact_id IS NULL AND organisation_id IS NOT NULL)', name='schedule_target_check'),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit_schedule',
    sa.Column('order_schedule_id', sa.Integer(), nullable=False),
    sa.Column('visit_type', sa.String(length=20), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('frequency', sqlalchemy_utils.types.choice.ChoiceType(length=255), nullable=False),
    sa.Column('custom_interval_days', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('visit_start_time', sa.Time(), nullable=True),
    sa.Column('visit_end_time', sa.Time(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_schedule_id'], ['order_schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_schedule')
    op.drop_table('order_schedule')
    # ### end Alembic commands ###
